name: run benchmark

on:
  workflow_dispatch:

jobs:
  soa-benchmark:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-benchmark:latest
    steps:
      - uses: actions/checkout@v4
      - name: build and compile
        run: |
          cmake -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build
      - name: run benchmarks
        run: python3 ${{github.workspace}}/build/plot.py
      - name: upload results
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build/*.png
      # - name: run soa_wrapper
      #   run: |
      #     ${{github.workspace}}/build/soa_wrapper
      # - name: run soa_boost
      #   run: |
      #     ${{github.workspace}}/build/soa_boost
