name: Run Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - 'chep2026'

jobs:
  soa-benchmark:
    name: soa-benchmark-${{ matrix.backend }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: cpu
            runner: cern-nextgen-h100
            cmake_targets: "aos_manual_cpu soa_manual_cpu aos_wrapper_cpu soa_wrapper_cpu soa_reflections_cpu"
          - backend: gpu
            runner: cern-nextgen-h100
            cmake_targets: "aos_manual_gpu soa_manual_gpu aos_wrapper_gpu soa_wrapper_gpu"
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-benchmark@sha256:02bfb50243942d8b203cd808a1bd4b856ee07fafb7022af76e7177aa4d322543
    env:
      BUILD_DIR: /root/build
      OUTPUT_DIR: /root/output
      PLOTS_DIR: /root/plots
      IMAGE_FILE_EXTENSION: png
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build and Compile (${{ matrix.backend }})
        run: |
          cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -B ${BUILD_DIR} -S ${GITHUB_WORKSPACE}
          cmake --build ${BUILD_DIR} --target ${{ matrix.cmake_targets }}

      - name: Run Benchmarks (${{ matrix.backend }})
        run: |
          mkdir -p ${OUTPUT_DIR} ${PLOTS_DIR}
          python3 ${GITHUB_WORKSPACE}/run_benchmarks.py --executables ${BUILD_DIR}/aos_*_${{ matrix.backend }} ${BUILD_DIR}/soa_*_${{ matrix.backend }} --output ${OUTPUT_DIR}

      - name: Plot AoS Large Benchmarks (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/aos_*_${{ matrix.backend }}.json"
          benchmarks: "Strided EasyRW InvariantMass Stencil"
          output: "${{ env.PLOTS_DIR }}/aos_${{ matrix.backend }}_large.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Plot AoS Small Benchmarks (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/aos_*_${{ matrix.backend }}.json"
          benchmarks: "EasyCompute RealRW HardRW NBody"
          output: "${{ env.PLOTS_DIR }}/aos_${{ matrix.backend }}_small.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Plot SoA Large Benchmarks (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/soa_*_${{ matrix.backend }}.json"
          benchmarks: "Strided EasyRW InvariantMass Stencil"
          output: "${{ env.PLOTS_DIR }}/soa_${{ matrix.backend }}_large.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Plot SoA Small Benchmarks (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/soa_*_${{ matrix.backend }}.json"
          benchmarks: "EasyCompute RealRW HardRW NBody"
          output: "${{ env.PLOTS_DIR }}/soa_${{ matrix.backend }}_small.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Plot Manual AoS vs SoA - Strided (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/*_manual_${{ matrix.backend }}.json"
          benchmarks: "Strided"
          output: "${{ env.PLOTS_DIR }}/manual_${{ matrix.backend }}_strided.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Plot Manual AoS vs SoA - Stencil (${{ matrix.backend }})
        uses: ./.github/actions/plot-benchmarks
        with:
          libraries: "${{ env.OUTPUT_DIR }}/*_manual_${{ matrix.backend }}.json"
          benchmarks: "Stencil"
          output: "${{ env.PLOTS_DIR }}/manual_${{ matrix.backend }}_stencil.${{ env.IMAGE_FILE_EXTENSION }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.backend }}-artifacts
          path: |
            ${{ env.PLOTS_DIR }}
            ${{ env.OUTPUT_DIR }}
