name: run benchmark with Clang P2996

on:
  workflow_dispatch:
  push:
    branches:
      - "p2996_refl"
      - "main"

env:
  CXX: /root/clang-p2996/build/bin/clang++
  CC: /root/clang-p2996/build/bin/clang
  LD_LIBRARY_PATH: /root/clang-p2996/build/lib/x86_64-unknown-linux-gnu/

jobs:
  soa-benchmark:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-benchmark:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: "p2996_refl"
      - name: rebuild google benchmark with libc++
        run: |
          dnf install -y libc++-devel
          cd /root/benchmark
          rm -rf build
          cmake -E make_directory "build"
          cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_ASSEMBLY_TESTS=off -DHAVE_STD_REGEX=on -DCMAKE_CXX_COMPILER=/root/clang-p2996/build/bin/clang++ -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_C_FLAGS="-stdlib=libc++" ../
          cmake --build "build" --config Release
          cmake -E chdir "build" ctest --build-config Release
          cmake --build "build" --config Release --target install
      - name: build and compile
        run: |
          cmake -DENABLE_CLANG_P2996=ON -DCMAKE_CXX_COMPILER=/root/clang-p2996/build/bin/clang++ -DCMAKE_C_COMPILER=/root/clang-p2996/build/bin/clang -B ${{github.workspace}}
          cmake --build ${{github.workspace}} --verbose -j$(nproc)
      - name: run benchmarks
        run: |
          python3 run_benchmarks.py ${{github.workspace}} refl/soa_versions_with_clang_p2996.csv
          python3 plot_benchmarks.py ${{github.workspace}} refl/soa_versions_with_clang_p2996.csv
          echo "Files in Workspace Directory:"
          ls -l ${{github.workspace}}
      - name: collect artifacts
        run: |
          mkdir soa-benchmark-results
          mv ${{github.workspace}}/*.png  soa-benchmark-results/
          mv ${{github.workspace}}/*.json soa-benchmark-results/
          mv ${{github.workspace}}/refl/*.json soa-benchmark-results/
          echo "Files in Results Directory:"
          ls -l soa-benchmark-results
      - name: upload results
        uses: actions/upload-artifact@v4
        with:
          name: soa-benchmark-results-${{ github.sha }}
          path: soa-benchmark-results
